swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }

parameters:
    mailer_transport: smtp
    mailer_host: 192.168.222.110
    mailer_user: null
    mailer_password: null
    mailer_port: 1025
