###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  redis:
    image: redis:alpine
    container_name: infomed-redis
    networks:
      work_net:
        ipv4_address: 192.168.222.103

  mysql:
    image: mysql:5.7
    container_name: infomed-mysql
    working_dir: /application
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=infomed
      - MYSQL_USER=infomed
      - MYSQL_PASSWORD=infomed
    ports:
      - "9901:3306"
    networks:
      work_net:
        ipv4_address: 192.168.222.102

  webserver:
    image: nginx:alpine
    container_name: infomed-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8801:80"
    networks:
      work_net:
        ipv4_address: 192.168.222.100

  php-fpm:
    build: phpdocker/php-fpm
    environment:
      MAILCATCHER_PORT_1025_TCP_ADDR: 1025
      MAILER_URL: smtp://192.168.222.110:1025
    links:
      - "mailcatcher:mailcatcher"
    container_name: infomed-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    networks:
      work_net:
        ipv4_address: 192.168.222.101
    expose:
      - 9003
      - 9000

  mailcatcher:
    image: dockage/mailcatcher:latest
    container_name: winfomed_mailcatcher
    ports:
      - "1080:1080"
      - "1025"
    networks:
      work_net:
        ipv4_address: 192.168.222.110

networks:
  work_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/24
